#
# $Id: GNUmakefile 19707 2010-10-29 17:59:36Z d3y133 $
#

 OBJ_OPTIMIZE = \
            nwpw_timing.o

	  OBJ = 

      LIBRARY = libnwpwlib.a

    USES_BLAS = nwpw_timing.F

  	LIB_DEFINES = 
	LIB_INCLUDES = -I../include


include ../../../config/makefile.h
include ../../../config/makelib.h

