#
# $Id: GNUmakefile 20974 2011-08-11 00:48:38Z bylaska $
#
 OBJ_OPTIMIZE = \
            c_coulomb.o \
            c_coulomb_screened.o

	  OBJ = 

      LIBRARY = libband.a

    USES_BLAS = c_coulomb.F c_coulomb_screened.F

  LIB_DEFINES = 


include ../../../../config/makefile.h
include ../../../../config/makelib.h

