#$Id: GNUmakefile 19708 2010-10-29 18:04:21Z d3y133 $

SUBDIRS = 

OBJ = socrates_input.o \
      socrates_driver.o \
      socrates_scf_ga.o

OBJ_OPTIMIZE = socrates_util.o

LIBRARY = libsocrates.a

USES_BLAS = 

LIB_DEFINES += -DDEBUG_PRINT -DDETAILED_FREE

HEADERS =

include ../config/makefile.h
include ../config/makelib.h

