#
# $Id: GNUmakefile 19707 2010-10-29 17:59:36Z d3y133 $
#

          OBJ_OPTIMIZE = paw_basis.o paw_small_basis.o paw_basis_data.o


      LIBRARY =	libpaw.a

   USES_BLAS = 

  LIB_INCLUDES = -I../include/

  LIB_DEFINES = 

  HEADERS = paw_basis.fh



include ../../../config/makefile.h
include ../../../config/makelib.h
include ../makefile.h












