#
# $Id: GNUmakefile 19707 2010-10-29 17:59:36Z d3y133 $
#

 OBJ_OPTIMIZE = \
		pspw_Grsm_list.o \
		pspw_lmbfgs.o \
		pspw_lmbfgs2.o \
		pspw_lmbfgs3.o \
		pspw_diis.o \
		pspw_rmmdiis.o



	  OBJ = 

      LIBRARY = libpspw.a

    USES_BLAS = pspw_lmbfgs.F pspw_lmbfgs2.F pspw_diis.F pspw_Grsm_list.F pspw_rmmdiis.F

  LIB_DEFINES = 


include ../../../../config/makefile.h
include ../../../../config/makelib.h

