#
# $Id: GNUmakefile 19707 2010-10-29 17:59:36Z d3y133 $
#

          OBJ_OPTIMIZE =  paw_spher_func.o paw_double_factorial.o paw_gamma_function.o \
                           paw_hypergeom1F1.o
          HEADERS = paw_spher_func.fh paw_gamma_function.fh paw_hypergeom.fh \
                              paw_double_factorial.fh


      LIBRARY =	libpaw.a

   USES_BLAS = 

  LIB_INCLUDES = 

  LIB_DEFINES = 




include ../../../config/makefile.h
include ../../../config/makelib.h


