#$Id: GNUmakefile 19708 2010-10-29 18:04:21Z d3y133 $
   OBJ_OPTIMIZE = gibbs.o

   OBJ = dntmc_input.o dntmc_setgeom.o

   LIBRARY = libdntmc.a
 USES_BLAS = gibbs.F

include ../config/makefile.h
include ../config/makelib.h
