#
# $Id: GNUmakefile 22503 2012-05-20 06:58:57Z d3y133 $
#
     SUBDIRS =


 OBJ_OPTIMIZE = \
		band_analysis.o \
                orb_pop_borb.o 


      LIBRARY = libband.a

    USES_BLAS =  band_analysis.F orb_pop_borb.F


  LIB_DEFINES = 


include ../../../config/makefile.h
include ../../../config/makelib.h

