#
# $Id: GNUmakefile 26411 2014-12-02 00:53:01Z bylaska $
#
 SUBDIRS = 

 OBJ_OPTIMIZE = pspw_hfx.o pspw_hfx_localized.o

	  OBJ = 

      LIBRARY = libpspw.a

    USES_BLAS = pspw_hfx.F pspw_hfx_localized.F

  LIB_DEFINES = 


include ../../../../config/makefile.h
include ../../../../config/makelib.h

