#
# $Id: GNUmakefile 20221 2011-04-20 01:59:21Z jhammond $
#
#
OBJ_OPTIMIZE=qhop_setup.o qhop_asite.o qhop_dsite.o qhop_prob.o qhop_init.o qhop_pindex.o qhop_final.o

LIBRARY=libqhop.a

HEADER=

USES_BLAS=

include ../config/makefile.h

include ../config/makelib.h
