#
# $Id: GNUmakefile 19707 2010-10-29 17:59:36Z d3y133 $
#
      SUBDIRS = lib kbpp makepsi cpsd cgsd analysis \
                cell_optimize qmmm charge dplot lcao


          OBJ = task_pspw.o


      LIBRARY =	libpspw.a

   USES_BLAS = 

  LIB_INCLUDES = 

  LIB_DEFINES = 




include ../../config/makefile.h
include ../../config/makelib.h









