#
# $Id: GNUmakefile 19708 2010-10-29 18:04:21Z d3y133 $
#

        OBJ = cphf.o \
              cphf_poliz.o \
	      cphf_solve.o \
	      cphf_solve2.o \
              cphf_solve3.o cphf_solve4.o



    LIBRARY = libcphf.a


include ../config/makefile.h
include ../config/makelib.h


