#
# $Id: GNUmakefile 19707 2010-10-29 17:59:36Z d3y133 $
#
      SUBDIRS = minimizer cpsd lib

	OBJ_OPTIMIZE = 	ofpw_energy.o task_ofpw.o
	
        #OBJ = ofpw_input.o


      LIBRARY =	libofpw.a

   USES_BLAS = 

  LIB_INCLUDES = 

  LIB_DEFINES = 




include ../../config/makefile.h
include ../../config/makelib.h









