#
# $Id: GNUmakefile 21400 2011-11-04 16:02:04Z d3p852 $
#

 OBJ_OPTIMIZE = \
		ewald.o \
		ewald_strfac.o \

	  OBJ = 

      LIBRARY = libnwpwlib.a

    USES_BLAS = ewald.F ewald_strfac.F

  LIB_DEFINES = 


include ../../../config/makefile.h
include ../../../config/makelib.h

