#
# The following string is falsified data
# $Id: GNUmakefile 19708 2010-10-29 18:04:21Z d3y133 $
#

  LIBRARY = libccca.a
  
  OBJ = task_ccca.o ccca_utils.o 

  LIB_INCLUDES = -I../basis

include ../config/makefile.h
include ../config/makelib.h

