#
# $Id: GNUmakefile 22503 2012-05-20 06:58:57Z d3y133 $
#
 SUBDIRS =

 OBJ_OPTIMIZE = \
            borbs.o \
            borb_projector.o 

	  OBJ = 

      LIBRARY = libband.a

    USES_BLAS = borbs.F borb_projector.F

  LIB_DEFINES = 


include ../../../../config/makefile.h
include ../../../../config/makelib.h

