#
# $Id: GNUmakefile 24448 2013-07-27 06:12:44Z d3y133 $
#
 OBJ_OPTIMIZE = nwpw_library.o nwpw_libfile.o nwpw_set_library.o


	  OBJ = 

      LIBRARY = libnwpwlib.a

    USES_BLAS = 

  LIB_INCLUDES = 

include ../../config/makefile.h
include ../../config/makelib.h









