#
# $Id: MakeFile 19707 2010-10-29 17:59:36Z d3y133 $
#

OBJ_OPTIMIZE = $(OBJDIR)\nwpw_library.obj \
               $(OBJDIR)\nwpw_libfile.obj


LIBRARY = nwpwlib.lib

LIB_DEFINES =  -DNWPW_LIBRARY="'$(SRCDIR)/nwpw/libraryps/'"

!INCLUDE ..\..\config\NTmakefile.h
!INCLUDE ..\..\config\NTmakelib.h
