#
# $Id: GNUmakefile 19707 2010-10-29 17:59:36Z d3y133 $
#

 OBJ_OPTIMIZE = \
            coulomb.o \
			coulomb2.o \
			coulomb_screened.o 



	  OBJ = 

      LIBRARY = libpspw.a

    USES_BLAS = coulomb.F coulomb2.F coulomb_screened.F 

  LIB_DEFINES = 


include ../../../../config/makefile.h
include ../../../../config/makelib.h

