#
# $Id: GNUmakefile 20307 2011-05-06 22:47:22Z d3p852 $
#

BLAS     = 
OBJ = cckohn.o cckohn_input.o cknew.o obftrans.o hbftrans.o \
	bforthog.o fforth1.o fforth2.o denom.o top.o
OBJ_OPTIMIZE = 

USES_BLAS = 

SUBDIRS = bessel

LIBRARY = libcckohn.a

include ../config/makefile.h
include ../config/makelib.h
