#
# $Id: GNUmakefile 19708 2010-10-29 18:04:21Z d3y133 $
#

 OBJ_OPTIMIZE =  task_chelp.o
       SUBDIRS = grid

LIBRARY=libchelp.a

HEADERS=

include ../config/makefile.h

include ../config/makelib.h
