#
# $Id: GNUmakefile 19707 2010-10-29 17:59:36Z d3y133 $
#

          OBJ = smd_input.o

      LIBRARY = libsmd.a

#  LIB_DEFINES = -DMPI -I$(MPI_INCLUDE)



include ../../config/makefile.h
include ../../config/makelib.h









