#
# $Id: GNUmakefile 19707 2010-10-29 17:59:36Z d3y133 $
#
 SUBDIRS = 
 OBJ_OPTIMIZE = \
                model_charge.o

      OBJ =


      LIBRARY = libpspw.a

    USES_BLAS = 
  LIB_DEFINES =
  LIB_INCLUDES = 

include ../../../../config/makefile.h
include ../../../../config/makelib.h

