#
# $Id: GNUmakefile 19708 2010-10-29 18:04:21Z d3y133 $
#

 OBJ_OPTIMIZE =  chelp_grid.o\
                 chelp_atom_rad.o\
                 chelp_grid_data.o

LIBRARY=libchelp.a

HEADERS=

include ../../config/makefile.h

include ../../config/makelib.h
