#
# $Id: GNUmakefile 19708 2010-10-29 18:04:21Z d3y133 $
#

OBJ = gg.o outward.o sjymec.o cckohn_spline.o splinec.o ubesplg.o\
	zero.o

OBJ_OPTIMIZE = 

LIBRARY = libcckohn.a

USES_BLAS = 

include ../../config/makefile.h
include ../../config/makelib.h

