#
# $Id: GNUmakefile 25011 2013-12-19 17:45:25Z d3y133 $
#

  OBJ_OPTIMIZE = wgc.o
  OBJ =

      LIBRARY = libofpw.a

    USES_BLAS = wgc.F

  LIB_DEFINES = 


include ../../../../config/makefile.h
include ../../../../config/makelib.h

