#
# $Id: GNUmakefile 21446 2011-11-07 23:56:30Z d3p852 $
#

  LIBRARY = libvscf.a
  
  OBJ = vscf_input.o \
        vscf.o

  USES_BLAS= vscf.F

include ../config/makefile.h
include ../config/makelib.h

