#
# $Id: GNUmakefile 19707 2010-10-29 17:59:36Z d3y133 $
#

          OBJ = task_smd_fragment.o  smd_monomer.o

      LIBRARY = libsmd.a

LIB_INCLUDES = -I../include
#  LIB_DEFINES = -DMPI -I$(MPI_INCLUDE)



include ../../config/makefile.h
include ../../config/makelib.h









