#
# $Id: GNUmakefile 26253 2014-09-12 17:35:12Z d3y133 $
#

#      SUBDIRS = pspw band nwpwlib libraryps
       SUBDIRS = nwpwlib libraryps pspw paw band ofpw

          OBJ = nwpw_input.o \
                nwpw_default.o \
                nwpw_vectors_input.o


      LIBRARY = libnwpw.a


  LIB_DEFINES =

      HEADERS = ../nwxc/nwxc.fh




include ../config/makefile.h
include ../config/makelib.h









