#
# $Id: GNUmakefile 19707 2010-10-29 17:59:36Z d3y133 $
#

 OBJ_OPTIMIZE = \
            cke.o



	  OBJ = 

      LIBRARY = libband.a

    USES_BLAS = cke.F

  LIB_DEFINES = 



include ../../../../config/makefile.h
include ../../../../config/makelib.h

