#
# $Id: GNUmakefile 25745 2014-06-08 07:46:01Z d3y133 $
#
      SUBDIRS = 

 OBJ_OPTIMIZE = \
		fmm.o

	  OBJ = 

      LIBRARY = libnwpwlib.a

    USES_BLAS = fmm.F

  LIB_DEFINES = 


include ../../../config/makefile.h
include ../../../config/makelib.h

