#
# $Id: GNUmakefile 19708 2010-10-29 18:04:21Z d3y133 $
#


   OBJ = nwnbo.o

   LIBRARY = libnbo.a
   LIB_DEFINES = 
   LIB_INCLUDES = -I../include

USES_BLAS = nwnbo.F

include ../config/makefile.h
include ../config/makelib.h
