
# $Id: GNUmakefile 25011 2013-12-19 17:45:25Z d3y133 $
#
 OBJ_OPTIMIZE = \
                pspw_Pair.o

	  OBJ = 


      LIBRARY = libpspw.a

    USES_BLAS = pspw_Pair.F
                
  LIB_DEFINES =


include ../../../../config/makefile.h
include ../../../../config/makelib.h

