#
# $Id: GNUmakefile 25011 2013-12-19 17:45:25Z d3y133 $
#

 OBJ_OPTIMIZE = \
		tamd_input.o \
		tamd.o

	  OBJ = 

      LIBRARY = libnwpwlib.a

    USES_BLAS = tamd.F

  LIB_DEFINES = 


include ../../../config/makefile.h
include ../../../config/makelib.h

