#
# $Id: GNUmakefile 19707 2010-10-29 17:59:36Z d3y133 $
#

#       SUBDIRS = smd-subgroups
#       SUBDIRS = smd-serial
       SUBDIRS = smddb smd-frag smd-energy smd-input smdlib 
#                 smd-scheduler
#       SUBDIRS = smd-parallel




include ../config/makefile.h
include ../config/makelib.h









