#
# $Id: GNUmakefile 19707 2010-10-29 17:59:36Z d3y133 $
#

          OBJ_OPTIMIZE = paw_energy_core_atom.o paw_matrix_core.o
          HEADERS = paw_energy_core_atom.fh 


      LIBRARY =	libpaw.a

   USES_BLAS = 

  LIB_INCLUDES = -I../include/

  LIB_DEFINES = 




include ../../../config/makefile.h
include ../../../config/makelib.h
include ../makefile.h


