#
# $Id: GNUmakefile 19707 2010-10-29 17:59:36Z d3y133 $
#

          OBJ_OPTIMIZE = paw_matrix_comp_pot.o paw_pot_comp.o
          HEADERS = paw_matrix_comp_pot.fh paw_pot_comp_data.fh
          

      LIBRARY =	libpaw.a

   USES_BLAS = 

  LIB_INCLUDES = 

  LIB_DEFINES = 





include ../../../config/makefile.h
include ../../../config/makelib.h

