
# $Id: GNUmakefile 19707 2010-10-29 17:59:36Z d3y133 $
#
 OBJ_OPTIMIZE = \
                pspw_Q.o

	  OBJ = 


      LIBRARY = libpspw.a

    USES_BLAS = pspw_Q.F
                
  LIB_DEFINES =


include ../../../../config/makefile.h
include ../../../../config/makelib.h

