#
# $Id: GNUmakefile 19707 2010-10-29 17:59:36Z d3y133 $
#

          OBJ_OPTIMIZE =  paw_comp_charge.o
          HEADERS = paw_comp_charge_data.fh


      LIBRARY =	libpaw.a

   USES_BLAS = 

  LIB_INCLUDES =

  LIB_DEFINES = 




include ../../../config/makefile.h
include ../../../config/makelib.h
include ../makefile.h


