
# $Id: GNUmakefile 19707 2010-10-29 17:59:36Z d3y133 $
#
 OBJ_OPTIMIZE = \
                fractional.o \
		frac_occ_input.o \
		frac_occ.o
 HEADERS = frac_occ.fh

	  OBJ = 

      LIBRARY = libnwpwlib.a

    USES_BLAS = fractional.F frac_occ.F
                

  LIB_DEFINES =


include ../../../config/makefile.h
include ../../../config/makelib.h

