#
# $Id: GNUmakefile 19707 2010-10-29 17:59:36Z d3y133 $
#
 SUBDIRS = psi electron ke coulomb exchange-correlation sic hfx ion psp Grsm_list aorbs truncating_function

include ../../../config/makefile.h
include ../../../config/makelib.h

