#$Id: GNUmakefile 19708 2010-10-29 18:04:21Z d3y133 $
   OBJ_OPTIMIZE = dc_energy.o

   OBJ = dc_initialize.o dc_setgeom.o

   LIBRARY = libdangchang.a

include ../config/makefile.h
include ../config/makelib.h


