#
# $Id: GNUmakefile 21400 2011-11-04 16:02:04Z d3p852 $
#

 OBJ_OPTIMIZE = \
            chi_H.o \
            chi_Hv4.o



	  OBJ = 

      LIBRARY = libofpw.a

    USES_BLAS = chi_H.F chi_Hv4.F

  LIB_DEFINES = 


include ../../../../config/makefile.h
include ../../../../config/makelib.h

