#
# $Id: GNUmakefile 19708 2010-10-29 18:04:21Z d3y133 $
#

  LIBRARY = libgeninterface.a
  
  OBJ = geninterface.o NWChemWrap.o

  HEADERS = geninterface.fh

include ../config/makefile.h
include ../config/makelib.h

