
# $Id: GNUmakefile 25011 2013-12-19 17:45:25Z d3y133 $
#
 OBJ_OPTIMIZE = \
                pspw_Three.o

	  OBJ = 


      LIBRARY = libpspw.a

    USES_BLAS = pspw_Three.F
                
  LIB_DEFINES =


include ../../../../config/makefile.h
include ../../../../config/makelib.h

