#
# $Id: GNUmakefile 19707 2010-10-29 17:59:36Z d3y133 $
#
 OBJ_OPTIMIZE = \
				band_dplot_input.o \
				band_dplot.o \
				band_dplot_iteration.o 


	  OBJ = 

      LIBRARY = libband.a

    USES_BLAS = band_dplot.F

  LIB_DEFINES = 


include ../../../config/makefile.h
include ../../../config/makelib.h

