c
c $Id: p_array.inc 19707 2010-10-29 17:59:36Z d3y133 $
c

      integer mxtype,mxatms,mxvlist,mxelist,mxnlist,mxkvect,mxpote
      integer mxcons,mxcons2,mxbond,mxbond2,mxshel,mxshel2

      parameter(mxtype=5)
      parameter(mxatms=2000)
      parameter(mxelist=200)
      parameter(mxvlist=200)
      parameter(mxnlist=500)
      parameter(mxkvect=25)
      parameter(mxpote=10)
      parameter(mxcons=5)
      parameter(mxcons2=1000)
      parameter(mxbond=5)
      parameter(mxbond2=500)
      parameter(mxshel=5)
      parameter(mxshel2=750)
