#
# $Id: GNUmakefile 19707 2010-10-29 17:59:36Z d3y133 $
#

          OBJ_OPTIMIZE =  paw_nonlocal.o 
          HEADERS = 


      LIBRARY =	libpaw.a

   USES_BLAS =  paw_nonlocal.F

  LIB_INCLUDES =

  LIB_DEFINES = 




include ../../../config/makefile.h
include ../../../config/makelib.h


