#
# $Id: GNUmakefile 19707 2010-10-29 17:59:36Z d3y133 $
#

 OBJ_OPTIMIZE = \
		chi_read.o \
		chi_write.o \
		chi_new.o \
		chi_expander.o

      LIBRARY = libofpw.a

    USES_BLAS = 

  LIB_DEFINES = 


include ../../../../config/makefile.h
include ../../../../config/makelib.h


