#
# $Id: GNUmakefile 21430 2011-11-07 21:59:54Z d3p852 $
#

 OBJ_OPTIMIZE = \
		c_electron.o \
                cpsi_H.o 



	  OBJ = 

      LIBRARY = libband.a

    USES_BLAS = c_electron.F psi_lmbda.f cpsi_H.F

  LIB_DEFINES = 


include ../../../../config/makefile.h
include ../../../../config/makelib.h

