#
# $Id: GNUmakefile 23626 2013-02-23 01:55:52Z bylaska $
#

 OBJ_OPTIMIZE = \
		nwpw_gaunt.o \
		nwpw_compcharge.o\
		nwpw_xc.o\
		nwpw_vosko.o\
		nwpw_gga.o\
		nwpw_SpecialKummer.o \
		nwpw_GaussBessel.o \
		nwpw_WGaussian.o

	  OBJ = 

      LIBRARY = libnwpwlib.a

    USES_BLAS = nwpw_gaunt.F nwpw_compcharge.F nwpw_xc.F

  LIB_DEFINES = 


include ../../../../config/makefile.h
include ../../../../config/makelib.h

