#
# $Id: GNUmakefile 19707 2010-10-29 17:59:36Z d3y133 $
#

 OBJ_OPTIMIZE = Pneb.o
 OBJ = 



      LIBRARY = libnwpwlib.a

    USES_BLAS = Pneb.F

  LIB_DEFINES = 

include ../../../config/makefile.h
include ../../../config/makelib.h







