#!/bin/bash
#
# $Id: domknwchemenv 24341 2013-06-22 03:42:03Z d3y133 $
#
#---   Set the appropriate environment variables for the tests.
#---   Environment variables are preferred to avoid clashes with other 
#---   calculation on the same machine so where possible we will use those
#
here="`pwd`"
export NWCHEM_NWPW_LIBRARY="${here}/../src/nwpw/libraryps/"
export NWCHEM_BASIS_LIBRARY="${here}/../src/basis/libraries/"
export NWCHEM_SCRATCH_DIR="${here}/scratchdir"
export NWCHEM_PERMANENT_DIR="${here}/scratchdir"
#export NWCHEM_MEMORY_TOTAL=65536000 # 500 MB
