#
# $Id: GNUmakefile 19707 2010-10-29 17:59:36Z d3y133 $
#

 OBJ_OPTIMIZE = \
		nose-hoover.o

	  OBJ = 

      LIBRARY = libnwpwlib.a

    USES_BLAS = nose-hoover.F

  LIB_DEFINES = 


include ../../../config/makefile.h
include ../../../config/makelib.h

