#
# $Id: GNUmakefile 25473 2014-04-09 23:50:11Z bylaska $
#

 OBJ_OPTIMIZE = \
		metadynamics_input.o \
		metadynamics_aux.o \
		metadynamics.o

	  OBJ = 

      LIBRARY = libnwpwlib.a

    USES_BLAS = metadynamics.F

  LIB_DEFINES = 


include ../../../config/makefile.h
include ../../../config/makelib.h

